import dayjs from "dayjs";

import {
  calculateAdherenceRate,
  calculateAverage,
  calculateCancellationRate,
  findMax,
  findMin,
  generateDateRange,
  groupByDay,
  groupByWeek,
  maskCPF,
} from "@/_lib/report-utils";
import type { Menu } from "@/_types/menu";
import type {
  ActiveUsersReportData,
  OperationalStatsReportData,
  PopularMenusReportData,
  ReportFilters,
  ReservationReportData,
  WasteReportData,
} from "@/_types/report";
import type { Reservation } from "@/_types/reservation";
import type { User } from "@/_types/user";

/**
 * Processes raw reservation data into report format
 * Aggregates reservations by day and week, calculates summary statistics
 * @param reservations - Array of reservations to process
 * @param filters - Report filters applied
 * @returns Processed reservation report data
 */
export function processReservationsData(
  reservations: Reservation[],
  filters: ReportFilters,
): ReservationReportData {
  // Apply additional filters
  let filteredReservations = reservations;

  // Filter by reservation type (automatic vs manual)
  if (filters.reservationType && filters.reservationType !== "ALL") {
    const isAutomatic = filters.reservationType === "AUTOMATIC";
    filteredReservations = filteredReservations.filter(
      (r) => r.isAutoGenerated === isAutomatic,
    );
  }

  // Calculate summary statistics
  const totalReservations = filteredReservations.length;
  const activeReservations = filteredReservations.filter(
    (r) => r.status === "ACTIVE",
  ).length;
  const cancelledReservations = filteredReservations.filter(
    (r) => r.status === "CANCELLED",
  ).length;
  const cancellationRate = calculateCancellationRate(
    totalReservations,
    cancelledReservations,
  );

  // Group by day for daily data
  const dailyGroups = groupByDay(
    filteredReservations as unknown as Record<string, unknown>[],
    "reservationDate",
  );
  const dateRange = generateDateRange(filters.startDate, filters.endDate);

  const dailyData = dateRange.map((date) => {
    const dayReservations = (dailyGroups[date] ||
      []) as unknown as Reservation[];
    return {
      date,
      total: dayReservations.length,
      confirmed: dayReservations.filter((r) => r.status === "ACTIVE").length,
      cancelled: dayReservations.filter((r) => r.status === "CANCELLED").length,
    };
  });

  // Group by week for weekly data
  const weeklyGroups = groupByWeek(
    filteredReservations as unknown as Record<string, unknown>[],
    "reservationDate",
  );
  const weeklyData = weeklyGroups.map((week) => ({
    weekStart: week.weekStart,
    weekEnd: week.weekEnd,
    total: week.items.length,
  }));

  // Format detailed reservations list
  const detailedReservations = filteredReservations
    .map((r) => ({
      id: r.id,
      date: r.reservationDate,
      userName: r.user?.name || "Usuário não encontrado",
      userCpf: maskCPF(r.user?.cpf || ""),
      menuSummary: getMenuSummary(r.menu),
      variation: r.menuVariation?.variationType || "STANDARD",
      status: r.status,
      isAutomatic: r.isAutoGenerated,
    }))
    .sort((a, b) => dayjs(b.date).diff(dayjs(a.date))); // Sort by date descending

  return {
    summary: {
      totalReservations,
      activeReservations,
      cancelledReservations,
      cancellationRate,
    },
    dailyData,
    weeklyData,
    reservations: detailedReservations,
  };
}

/**
 * Processes menu and reservation data to find popular menus
 * Creates ranking of menus by reservation count and calculates adherence rates
 * @param reservations - Array of reservations
 * @param menus - Array of menus
 * @returns Processed popular menus report data
 */
export function processPopularMenusData(
  reservations: Reservation[],
  menus: Menu[],
): PopularMenusReportData {
  // Count reservations per menu
  const menuReservationCounts = new Map<string, number>();
  reservations.forEach((r) => {
    const count = menuReservationCounts.get(r.menuId) || 0;
    menuReservationCounts.set(r.menuId, count + 1);
  });

  // Build menu data with reservation counts
  const menusWithData = menus
    .map((menu) => {
      const totalReservations = menuReservationCounts.get(menu.id) || 0;
      const menuReservations = reservations.filter((r) => r.menuId === menu.id);

      // Calculate variation distribution
      const standardCount = menuReservations.filter(
        (r) => r.menuVariation?.variationType === "STANDARD",
      ).length;
      const withEggCount = menuReservations.filter(
        (r) => r.menuVariation?.variationType === "EGG_SUBSTITUTE",
      ).length;

      // Get menu composition grouped by category
      const composition = getMenuComposition(menu);

      return {
        menuId: menu.id,
        date: menu.date,
        dayOfWeek: translateDayOfWeek(menu.dayOfWeek),
        summary: getMenuSummary(menu),
        totalReservations,
        adherenceRate: 0, // Will be calculated if we have total users
        composition,
        variationDistribution: {
          standard: standardCount,
          withEgg: withEggCount,
        },
      };
    })
    .sort((a, b) => b.totalReservations - a.totalReservations)
    .slice(0, 10); // Top 10

  return {
    summary: {
      totalMenus: menus.length,
      totalReservations: reservations.length,
      averageReservationsPerMenu:
        menus.length > 0
          ? Number((reservations.length / menus.length).toFixed(2))
          : 0,
    },
    topMenus: menusWithData,
  };
}

/**
 * Processes user and reservation data to find active users
 * Calculates user engagement statistics and identifies patterns
 * @param reservations - Array of reservations
 * @param users - Array of users
 * @param filters - Report filters applied
 * @returns Processed active users report data
 */
export function processActiveUsersData(
  reservations: Reservation[],
  users: User[],
  filters: ReportFilters,
): ActiveUsersReportData {
  // Filter users by type if specified
  let filteredUsers = users;
  if (filters.userType && filters.userType !== "ALL") {
    filteredUsers = users.filter((u) => u.userType === filters.userType);
  }

  // Count reservations per user
  const userReservations = new Map<string, Reservation[]>();
  reservations.forEach((r) => {
    if (!userReservations.has(r.userId)) {
      userReservations.set(r.userId, []);
    }
    userReservations.get(r.userId)!.push(r);
  });

  // Calculate user statistics
  const usersWithStats = Array.from(userReservations.entries())
    .map(([userId, userReservationsList]) => {
      const user = users.find((u) => u.id === userId);
      if (!user) return null;

      // Filter by user type if needed
      if (
        filters.userType &&
        filters.userType !== "ALL" &&
        user.userType !== filters.userType
      ) {
        return null;
      }

      const totalReservations = userReservationsList.length;
      const cancelledReservations = userReservationsList.filter(
        (r) => r.status === "CANCELLED",
      ).length;
      const cancellationRate = calculateCancellationRate(
        totalReservations,
        cancelledReservations,
      );

      return {
        userId: user.id,
        name: user.name,
        cpf: maskCPF(user.cpf),
        userType: user.userType,
        totalReservations,
        cancelledReservations,
        cancellationRate,
      };
    })
    .filter((u) => u !== null)
    .sort((a, b) => b!.totalReservations - a!.totalReservations);

  // Calculate type distribution
  const fixoCount = usersWithStats.filter((u) => u!.userType === "FIXO").length;
  const naoFixoCount = usersWithStats.filter(
    (u) => u!.userType === "NAO_FIXO",
  ).length;

  const totalActiveUsers = usersWithStats.length;
  const totalRegisteredUsers = filteredUsers.length;
  const adherenceRate = calculateAdherenceRate(
    totalActiveUsers,
    totalRegisteredUsers,
  );

  return {
    summary: {
      totalActiveUsers,
      totalRegisteredUsers,
      adherenceRate,
    },
    userTypeDistribution: {
      fixo: fixoCount,
      naoFixo: naoFixoCount,
    },
    users: usersWithStats as ActiveUsersReportData["users"],
  };
}

/**
 * Processes all data to generate operational statistics
 * Provides comprehensive metrics about system usage and performance
 * @param reservations - Array of reservations
 * @param users - Array of users
 * @param menus - Array of menus
 * @param filters - Report filters applied
 * @returns Processed operational stats report data
 */
export function processOperationalStatsData(
  reservations: Reservation[],
  users: User[],
  menus: Menu[],
  filters: ReportFilters,
): OperationalStatsReportData {
  // Reservation metrics
  const totalReservations = reservations.length;
  const dateRange = generateDateRange(filters.startDate, filters.endDate);
  const dailyAverage = totalReservations / dateRange.length;

  const dailyGroups = groupByDay(
    reservations as unknown as Record<string, unknown>[],
    "reservationDate",
  );
  const dailyCounts = dateRange.map((date) => ({
    date,
    count: (dailyGroups[date] || []).length,
  }));

  const peakDay = findMax(dailyCounts, "count") || { date: "", count: 0 };
  const lowestDay = findMin(dailyCounts, "count") || { date: "", count: 0 };

  // User metrics
  const activeUserIds = new Set(reservations.map((r) => r.userId));
  const totalActive = activeUserIds.size;
  const adherenceRate = calculateAdherenceRate(totalActive, users.length);

  // Calculate new users (users created within the period)
  const newUsers = users.filter((u) => {
    const createdDate = dayjs(u.createdAt).format("YYYY-MM-DD");
    return (
      dayjs(createdDate).isSameOrAfter(filters.startDate) &&
      dayjs(createdDate).isSameOrBefore(filters.endDate)
    );
  }).length;

  // Menu metrics
  const menuReservationCounts = new Map<string, number>();
  reservations.forEach((r) => {
    const count = menuReservationCounts.get(r.menuId) || 0;
    menuReservationCounts.set(r.menuId, count + 1);
  });

  const mostPopularMenuEntry = Array.from(menuReservationCounts.entries()).sort(
    (a, b) => b[1] - a[1],
  )[0];

  const mostPopularMenu = mostPopularMenuEntry
    ? {
        date: menus.find((m) => m.id === mostPopularMenuEntry[0])?.date || "",
        reservations: mostPopularMenuEntry[1],
      }
    : { date: "", reservations: 0 };

  // Cancellation metrics
  const cancelledReservations = reservations.filter(
    (r) => r.status === "CANCELLED",
  );
  const cancellationRate = calculateCancellationRate(
    totalReservations,
    cancelledReservations.length,
  );

  // Calculate average cancellation time (time between creation and cancellation)
  const cancellationTimes = cancelledReservations
    .map((r) => {
      const created = dayjs(r.createdAt);
      const updated = dayjs(r.updatedAt);
      return updated.diff(created, "hour");
    })
    .filter((hours) => hours >= 0);

  const averageTime =
    cancellationTimes.length > 0
      ? `${calculateAverage(cancellationTimes).toFixed(1)} horas`
      : "N/A";

  // Day of week distribution
  const dayOfWeekCounts = new Map<string, number>();
  reservations.forEach((r) => {
    const dayOfWeek = dayjs(r.reservationDate).format("dddd");
    const count = dayOfWeekCounts.get(dayOfWeek) || 0;
    dayOfWeekCounts.set(dayOfWeek, count + 1);
  });

  const dayOfWeekDistribution = Array.from(dayOfWeekCounts.entries()).map(
    ([dayOfWeek, count]) => ({
      dayOfWeek:
        dayOfWeek.charAt(0).toUpperCase() + dayOfWeek.slice(1).toLowerCase(),
      count,
    }),
  );

  // Variation distribution
  const standardCount = reservations.filter(
    (r) => r.menuVariation?.variationType === "STANDARD",
  ).length;
  const withEggCount = reservations.filter(
    (r) => r.menuVariation?.variationType === "EGG_SUBSTITUTE",
  ).length;

  // Growth trend (compare with previous period)
  // Note: We would need to fetch previous period data to calculate this accurately
  // For now, we'll set it to 0 as a placeholder
  const growthTrend = {
    currentPeriod: totalReservations,
    previousPeriod: 0,
    percentageChange: 0,
  };

  return {
    reservationMetrics: {
      total: totalReservations,
      dailyAverage: Number(dailyAverage.toFixed(2)),
      peakDay,
      lowestDay,
    },
    userMetrics: {
      totalActive,
      adherenceRate,
      newUsers,
    },
    menuMetrics: {
      totalMenus: menus.length,
      averageReservationsPerMenu:
        menus.length > 0
          ? Number((totalReservations / menus.length).toFixed(2))
          : 0,
      mostPopularMenu,
    },
    cancellationMetrics: {
      total: cancelledReservations.length,
      rate: cancellationRate,
      averageTime,
    },
    dayOfWeekDistribution,
    variationDistribution: {
      standard: standardCount,
      withEgg: withEggCount,
    },
    growthTrend,
  };
}

/**
 * Processes cancellation data to generate waste report
 * Analyzes cancellation patterns and identifies waste opportunities
 * @param cancelledReservations - Array of cancelled reservations
 * @param filters - Report filters applied
 * @returns Processed waste report data
 */
export function processWasteData(
  cancelledReservations: Reservation[],
  filters: ReportFilters,
): WasteReportData {
  const totalCancellations = cancelledReservations.length;

  // Calculate cancellation rate (need to fetch all reservations for accurate rate)
  // For now, we'll calculate based on cancelled only
  const cancellationRate = 100; // All fetched reservations are cancelled

  // Estimate waste cost (assuming R$ 15 per meal)
  const estimatedWasteCost = totalCancellations * 15;

  // Time distribution (before/after 8:30 AM deadline)
  const deadline = "08:30";
  let beforeDeadline = 0;
  let afterDeadline = 0;

  cancelledReservations.forEach((r) => {
    const reservationDate = dayjs(r.reservationDate);
    const updatedTime = dayjs(r.updatedAt);

    // Check if cancellation was on the same day as reservation
    if (reservationDate.isSame(updatedTime, "day")) {
      const cancelTime = updatedTime.format("HH:mm");
      if (cancelTime <= deadline) {
        beforeDeadline++;
      } else {
        afterDeadline++;
      }
    } else if (updatedTime.isBefore(reservationDate)) {
      // Cancelled before the reservation date
      beforeDeadline++;
    } else {
      // Cancelled after the reservation date
      afterDeadline++;
    }
  });

  // Top cancellers
  const userCancellations = new Map<string, Reservation[]>();
  cancelledReservations.forEach((r) => {
    if (!userCancellations.has(r.userId)) {
      userCancellations.set(r.userId, []);
    }
    userCancellations.get(r.userId)!.push(r);
  });

  const topCancellers = Array.from(userCancellations.entries())
    .map(([userId, userCancelledReservations]) => {
      const user = userCancelledReservations[0]?.user;
      if (!user) return null;

      return {
        userId,
        userName: user.name,
        userCpf: maskCPF(user.cpf),
        totalCancellations: userCancelledReservations.length,
        cancellationRate: 100, // We only have cancelled data
      };
    })
    .filter((u) => u !== null)
    .sort((a, b) => b!.totalCancellations - a!.totalCancellations)
    .slice(0, 10);

  // Daily trend
  const dailyGroups = groupByDay(
    cancelledReservations as unknown as Record<string, unknown>[],
    "reservationDate",
  );
  const dateRange = generateDateRange(filters.startDate, filters.endDate);

  const dailyTrend = dateRange.map((date) => ({
    date,
    cancellations: (dailyGroups[date] || []).length,
  }));

  // Patterns analysis
  // Last minute cancellations (within 2 hours of deadline on same day)
  const lastMinuteCancellations = cancelledReservations.filter((r) => {
    const reservationDate = dayjs(r.reservationDate);
    const updatedTime = dayjs(r.updatedAt);

    if (!reservationDate.isSame(updatedTime, "day")) return false;

    const cancelTime = updatedTime.format("HH:mm");
    return cancelTime >= "06:30" && cancelTime <= deadline;
  }).length;

  // Recurring cancellers (users with more than 3 cancellations)
  const recurringCancellers = Array.from(userCancellations.values()).filter(
    (cancellations) => cancellations.length > 3,
  ).length;

  return {
    summary: {
      totalCancellations,
      cancellationRate,
      estimatedWasteCost,
    },
    timeDistribution: {
      beforeDeadline,
      afterDeadline,
    },
    topCancellers: topCancellers as WasteReportData["topCancellers"],
    dailyTrend,
    patterns: {
      lastMinuteCancellations,
      recurringCancellers,
    },
  };
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Generates a summary string for a menu
 * Prioritizes protein items, falls back to first 2 items
 * @param menu - Menu object
 * @returns Summary string
 */
function getMenuSummary(menu: Menu): string {
  if (!menu.menuCompositions || menu.menuCompositions.length === 0) {
    return "Cardápio sem itens";
  }

  const proteins = menu.menuCompositions
    .filter((mc) => mc.isMainProtein || mc.isAlternativeProtein)
    .map((mc) => mc.menuItem.name);

  if (proteins.length > 0) {
    return proteins.join(" / ");
  }

  // If no proteins, show first 2 items
  return menu.menuCompositions
    .slice(0, 2)
    .map((mc) => mc.menuItem.name)
    .join(", ");
}

/**
 * Gets menu composition grouped by category
 * @param menu - Menu object
 * @returns Array of categories with their items
 */
function getMenuComposition(
  menu: Menu,
): Array<{ categoryName: string; items: string[] }> {
  const categoryMap = new Map<string, string[]>();

  menu.menuCompositions.forEach((mc) => {
    const categoryName = mc.menuItem.category?.name || "Outros";
    if (!categoryMap.has(categoryName)) {
      categoryMap.set(categoryName, []);
    }
    categoryMap.get(categoryName)!.push(mc.menuItem.name);
  });

  return Array.from(categoryMap.entries()).map(([categoryName, items]) => ({
    categoryName,
    items,
  }));
}

/**
 * Translates day of week from English to Portuguese
 * @param dayOfWeek - Day of week in English (e.g., "MONDAY")
 * @returns Day of week in Portuguese (e.g., "Segunda-feira")
 */
function translateDayOfWeek(dayOfWeek: string): string {
  const translations: Record<string, string> = {
    MONDAY: "Segunda-feira",
    TUESDAY: "Terça-feira",
    WEDNESDAY: "Quarta-feira",
    THURSDAY: "Quinta-feira",
    FRIDAY: "Sexta-feira",
    SATURDAY: "Sábado",
    SUNDAY: "Domingo",
  };

  return translations[dayOfWeek] || dayOfWeek;
}
