import { Menu, MenuVariation } from "./menu";
import { User } from "./user";

export type ReservationStatus = "ACTIVE" | "CANCELLED";

export interface Reservation {
  id: string;
  userId: string;
  user?: User;
  menuId: string;
  menu: Menu;
  menuVariationId: string;
  menuVariation: MenuVariation;
  reservationDate: string;
  status: ReservationStatus;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateReservationRequest {
  menuId: string;
  menuVariationId: string;
  reservationDate: string;
}

export interface UpdateReservationRequest {
  menuVariationId: string;
}
