import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import React from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";

import type { Reservation } from "@/_types/reservation";

// Mock dependencies
vi.mock("@/_lib/date-utils", () => ({
  isBeforeCutoffTime: () => true,
  formatDateBR: () => "01/12/2025",
}));

vi.mock("sonner", () => ({
  toast: {
    success: vi.fn(),
    error: vi.fn(),
  },
}));

const mockReservation: Reservation = {
  id: "res-1",
  userId: "user-1",
  menuId: "menu-1",
  menu: {
    id: "menu-1",
    date: "2025-12-01",
    dayOfWeek: "MONDAY",
    weekNumber: 48,
    observations: null,
    isActive: true,
    menuCompositions: [],
    variations: [],
    createdAt: "2025-01-01",
    updatedAt: "2025-01-01",
  },
  menuVariationId: "var-1",
  menuVariation: {
    id: "var-1",
    menuId: "menu-1",
    variationType: "STANDARD",
    isDefault: true,
    proteinItem: null,
    createdAt: "2025-01-01",
  },
  reservationDate: "2025-12-01",
  status: "ACTIVE",
  isAutoGenerated: false,
  createdAt: "2025-11-17",
  updatedAt: "2025-11-17",
};

// Mock component that simulates cancel button behavior
const MockCancelReservationButton = ({
  onSuccess,
  mockMutate,
  isPending,
}: {
  onSuccess: () => void;
  mockMutate: (id: string, callbacks: any) => void;
  isPending: boolean;
}) => {
  const [isOpen, setIsOpen] = React.useState(false);

  const handleCancel = () => {
    mockMutate("res-1", {
      onSuccess: () => {
        onSuccess();
        setIsOpen(false);
      },
    });
  };

  return (
    <div>
      <button onClick={() => setIsOpen(true)}>Cancelar Reserva</button>
      {isOpen && (
        <div role="dialog">
          <h2>Confirmar Cancelamento</h2>
          <p>Tem certeza que deseja cancelar esta reserva?</p>
          <button onClick={() => setIsOpen(false)}>Não</button>
          <button onClick={handleCancel} disabled={isPending}>
            {isPending ? "Cancelando..." : "Sim, Cancelar"}
          </button>
        </div>
      )}
    </div>
  );
};

describe("Reservation Cancellation Flow Integration", () => {
  let queryClient: QueryClient;

  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
        mutations: { retry: false },
      },
    });
    vi.clearAllMocks();
  });

  const renderWithProviders = (ui: React.ReactElement) => {
    return render(
      <QueryClientProvider client={queryClient}>{ui}</QueryClientProvider>,
    );
  };

  it("deve cancelar reserva com sucesso após confirmação", async () => {
    const user = userEvent.setup();
    const onSuccess = vi.fn();
    const mockMutate = vi.fn((id, callbacks) => {
      if (callbacks?.onSuccess) {
        callbacks.onSuccess();
      }
    });

    renderWithProviders(
      <MockCancelReservationButton
        onSuccess={onSuccess}
        mockMutate={mockMutate}
        isPending={false}
      />,
    );

    // Clicar no botão de cancelar
    const cancelButton = screen.getByRole("button", {
      name: /cancelar reserva/i,
    });
    await user.click(cancelButton);

    // Verificar que o dialog de confirmação é exibido
    expect(
      screen.getByText(/tem certeza que deseja cancelar/i),
    ).toBeInTheDocument();

    // Confirmar cancelamento
    const confirmButton = screen.getByRole("button", {
      name: /sim, cancelar/i,
    });
    await user.click(confirmButton);

    // Verificar que a mutation foi chamada
    await waitFor(() => {
      expect(mockMutate).toHaveBeenCalledWith("res-1", expect.any(Object));
    });

    // Verificar que o callback de sucesso foi chamado
    await waitFor(() => {
      expect(onSuccess).toHaveBeenCalled();
    });
  });

  it("deve fechar dialog sem cancelar quando usuário clica em 'Não'", async () => {
    const user = userEvent.setup();
    const onSuccess = vi.fn();
    const mockMutate = vi.fn();

    renderWithProviders(
      <MockCancelReservationButton
        onSuccess={onSuccess}
        mockMutate={mockMutate}
        isPending={false}
      />,
    );

    // Clicar no botão de cancelar
    const cancelButton = screen.getByRole("button", {
      name: /cancelar reserva/i,
    });
    await user.click(cancelButton);

    // Verificar que o dialog é exibido
    expect(
      screen.getByText(/tem certeza que deseja cancelar/i),
    ).toBeInTheDocument();

    // Clicar em "Não"
    const noButton = screen.getByRole("button", { name: /não/i });
    await user.click(noButton);

    // Verificar que a mutation não foi chamada
    expect(mockMutate).not.toHaveBeenCalled();

    // Verificar que o callback de sucesso não foi chamado
    expect(onSuccess).not.toHaveBeenCalled();

    // Verificar que o dialog foi fechado
    await waitFor(() => {
      expect(
        screen.queryByText(/tem certeza que deseja cancelar/i),
      ).not.toBeInTheDocument();
    });
  });

  it("deve desabilitar botão durante o cancelamento", async () => {
    const user = userEvent.setup();
    const mockMutate = vi.fn();

    renderWithProviders(
      <MockCancelReservationButton
        onSuccess={() => {}}
        mockMutate={mockMutate}
        isPending={true}
      />,
    );

    // Clicar no botão de cancelar
    const cancelButton = screen.getByRole("button", {
      name: /cancelar reserva/i,
    });
    await user.click(cancelButton);

    // Verificar que o botão de confirmação está desabilitado
    const confirmButton = screen.getByRole("button", {
      name: /cancelando/i,
    });
    expect(confirmButton).toBeDisabled();
  });
});
