"use client";

import { ColumnDef } from "@tanstack/react-table";
import { ArrowUpDown } from "lucide-react";

import { Badge } from "@/_components/ui/badge";
import { Button } from "@/_components/ui/button";
import { formatDateBR } from "@/_lib/date-utils";
import { Reservation } from "@/_types/reservation";

import MyReservationsTableActions from "./table-actions";

const statusLabels: Record<string, string> = {
  ACTIVE: "Ativa",
  CANCELLED: "Cancelada",
};

const statusVariants: Record<string, "default" | "destructive"> = {
  ACTIVE: "default",
  CANCELLED: "destructive",
};

export const myReservationsTableColumns: ColumnDef<Reservation>[] = [
  {
    id: "reservationDate",
    accessorKey: "reservationDate",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
        >
          Data
          <ArrowUpDown className="ml-2 h-4 w-4" />
        </Button>
      );
    },
    cell: ({ row }) => {
      const date = row.getValue("reservationDate") as string;
      return formatDateBR(date);
    },
  },
  {
    id: "menu",
    header: "Cardápio",
    cell: ({ row }) => {
      const reservation = row.original;
      const mainProtein = reservation.menu?.menuCompositions?.find(
        (comp) => comp.isMainProtein,
      );
      const itemsCount = reservation.menu?.menuCompositions?.length || 0;

      return (
        <div className="flex flex-col">
          <span className="font-medium">
            {mainProtein?.menuItem?.name || "Cardápio"}
          </span>
          <span className="text-muted-foreground text-sm">
            {itemsCount} {itemsCount === 1 ? "item" : "itens"}
          </span>
        </div>
      );
    },
  },
  {
    id: "variation",
    header: "Variação",
    cell: ({ row }) => {
      const variation = row.original.menuVariation;
      if (!variation) return "-";

      const variationLabels: Record<string, string> = {
        STANDARD: "Padrão",
        EGG_SUBSTITUTE: "Com Ovo",
        VEGETARIAN: "Vegetariano",
      };

      return (
        variationLabels[variation.variationType] || variation.variationType
      );
    },
  },
  {
    id: "status",
    accessorKey: "status",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
        >
          Status
          <ArrowUpDown className="ml-2 h-4 w-4" />
        </Button>
      );
    },
    cell: ({ row }) => {
      const status = row.getValue("status") as string;
      return (
        <Badge variant={statusVariants[status]}>
          {statusLabels[status] || status}
        </Badge>
      );
    },
  },
  {
    id: "isAutoGenerated",
    accessorKey: "isAutoGenerated",
    header: "Auto",
    cell: ({ row }) => {
      const isAuto = row.getValue("isAutoGenerated") as boolean;
      return isAuto ? (
        <Badge variant="outline" className="bg-blue-50 dark:bg-blue-950">
          Auto
        </Badge>
      ) : null;
    },
  },
  {
    id: "actions",
    header: "Ações",
    cell: (params) => {
      const reservation = params.row.original;
      return <MyReservationsTableActions reservation={reservation} />;
    },
  },
];
